AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  HelloWorldFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: target/lambda.jar
      Handler: org.tsd.gutenberg.GutenbergRequestHandler
      Runtime: java11
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          MY_VARIABLE: 'my-value'
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
