name: Build and deploy to AWS Lambda

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'

      - name: Build JAR
        run: |
          mvn clean install

      - name: Install AWS CLI
        run: |
          sudo apt-get update && \
          sudo apt-get install -y python3-pip && \
          pip3 install awscli --upgrade --user && \
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc && \
          source ~/.bashrc

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Package for AWS Lambda
        run: |
          aws cloudformation package \
            --template-file aws/lambda_template.yml \
            --s3-bucket gutenberg-poc \
            --output-template-file packaged.yaml

      - name: Deploy to AWS Lambda
        id: aws-lambda-deploy
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: gutenberg-poc-stack
          template: packaged.yaml
          no-fail-on-empty-changeset: "1"
          capabilities: "CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND"

#      - name: Deploy to AWS Lambda
#        run: |
#          aws cloudformation package \
#            --template-file aws/lambda_template.yml \
#            --s3-bucket gutenberg-poc \
#            --output-template-file packaged.yaml
#          aws cloudformation deploy \
#            --template-file packaged.yaml \
#            --stack-name gutenberg-poc-stack \
#            --capabilities CAPABILITY_IAM
